project_id = "vcycuilwoplwghxsplew"

[functions.verify-razorpay-payment]
verify_jwt = false

[functions.create-razorpay-order]
verify_jwt = false

[functions.send-emergency-alert]
verify_jwt = false

